<?php 
/**
 * This file has been auto-generated by the project in production-mode
 * and is intended to store data permanently without expiration.*/

declare( strict_types = 1 ); 

return array (
  0 => 'Pangolia\\ContainerTests\\Mocks\\TestComponentA',
  1 => 'Pangolia\\ContainerTests\\Mocks\\TestComponentB',
  2 => 'Pangolia\\ContainerTests\\Mocks\\TestComponentC',
  3 => 'Pangolia\\ContainerTests\\Mocks\\Modules\\ModuleA\\TestModuleAComponentA',
  4 => 'Pangolia\\ContainerTests\\Mocks\\Modules\\ModuleA\\TestModuleAComponentB',
);